# TensorRT-YOLOConfig.cmake.in
# - This file is generated by CMake and should not be edited manually.

# Set the package version
set(TensorRT-YOLO_VERSION "6.4.0")

# Set the root directory of the package
set(TensorRT-YOLO_DIRS "/home/dys/code/TensorRT-YOLO/install")

# Set the include directory
set(TensorRT-YOLO_INCLUDE_DIRS "/home/dys/code/TensorRT-YOLO/install/include")

# Set the library directory
set(TensorRT-YOLO_LIBRARY_DIRS "/home/dys/code/TensorRT-YOLO/install/lib")

# Set the library dependencies
set(TensorRT-YOLO_LIBs "trtyolo")

# Add the library directories to the linker
link_directories("${TensorRT-YOLO_LIBRARY_DIRS}")

# Print the found information
message(STATUS "Found TensorRT-YOLO: ${TensorRT-YOLO_DIRS} (found version \"${TensorRT-YOLO_VERSION}\")")
